# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Twitteroffapp' do

pod 'TwitterKit', '~> 2.0'
pod 'ReactiveCocoa', '2.5'
pod 'MagicalRecord', '~> 2.3'
pod 'Reachability', '~> 3.2'
pod 'SVProgressHUD', '~> 2.0'

end

target 'TwitteroffappTests'  do

pod 'Kiwi', '~> 2.4'

end

